version: 2

models:
  - name: companies_stg
    columns:
      - name: company_id
        tests:
          - unique
          - not_null
      - name: company_country
        tests:
          - accepted_values:
              values:
                - BR
                - MX
                - CO
      - name: company_id
        tests:
          - relationships:
              to: ref('companies_deals_associations_stg')
              field: company_id
  - name: contacts_stg
    columns:
      - name: contact_id
        tests:
          - unique
          - not_null
      - name: contact_id
        tests:
          - relationships:
              to: ref('contacts_deals_associations_stg')
              field: contact_id
  - name: customers_stg
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_owner_id
        tests:
          - relationships:
              to: ref('owners_stg')
              field: owner_id
  - name: owners_stg
    columns:
      - name: owner_id
        tests:
          - unique
          - not_null
  - name: deals_stg
    columns:
      - name: deal_id
        tests:
          - unique
          - not_null
      - name: deal_owner_id
        tests:
          - relationships:
              to: ref('owners_stg')
              field: owner_id
      - name: deal_id
        tests:
          - relationships:
              to: ref('companies_deals_associations_stg')
              field: deal_id
      - name: deal_id
        tests:
          - relationships:
              to: ref('contacts_deals_associations_stg')
              field: deal_id
  - name: contacts_deals_associations_stg
    columns:
      - name: contact_id
        tests:
          - not_null
      - name: deal_id
        tests:
          - unique
          - not_null
  - name: companies_deals_associations_stg
    columns:
      - name: company_id
        tests:
          - not_null
      - name: deal_id
        tests:
          - unique
          - not_null